package banco;

import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class TelaBanco extends javax.swing.JFrame {

    ArrayList<Conta> contas;
    ArrayList<Cliente> cliente;
    ArrayList<Funcionario> funcionarios;
    
    public TelaBanco(ArrayList<Conta> contas, ArrayList<Funcionario> funcionarios) {
        this.contas = contas;
        this.funcionarios = funcionarios;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFormasPagamento = new javax.swing.ButtonGroup();
        jPanel_cadastro = new javax.swing.JPanel();
        agencia = new javax.swing.JLabel();
        inputAgencia = new javax.swing.JTextField();
        numero = new javax.swing.JLabel();
        inputNumero = new javax.swing.JTextField();
        saldo = new javax.swing.JLabel();
        inputSaldo = new javax.swing.JTextField();
        inputLimite = new javax.swing.JTextField();
        limite = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCadastroContas = new javax.swing.JTextArea();
        nome = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        inputCPF = new javax.swing.JTextField();
        cpf = new javax.swing.JLabel();
        inputEndereco = new javax.swing.JTextField();
        endereco = new javax.swing.JLabel();
        inputTelefone = new javax.swing.JTextField();
        telefone = new javax.swing.JLabel();
        listarContas = new javax.swing.JButton();
        buttonLimparCampos = new javax.swing.JButton();
        salvarContas = new javax.swing.JButton();
        jPanel_exclusao_contas = new javax.swing.JPanel();
        comboBoxContas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        buttonExcluirConta = new javax.swing.JButton();
        buttonEditarConta1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTitulares = new javax.swing.JList<>();
        jButtonEditTitular = new javax.swing.JButton();
        jButtonAddTitular = new javax.swing.JButton();
        jButtonExcluiTitular = new javax.swing.JButton();
        jButtonLog = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxFuncionarios = new javax.swing.JComboBox<>();
        jLabelFuncionario = new javax.swing.JLabel();
        jRadioButtonDepositar = new javax.swing.JRadioButton();
        jRadioButtonSacar = new javax.swing.JRadioButton();
        jRadioButtonTransferir = new javax.swing.JRadioButton();
        jLabelContaDestino = new javax.swing.JLabel();
        jComboBoxContaDestino = new javax.swing.JComboBox<>();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jButtonExecutarOperacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banco Marcos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("framePrincipal"); // NOI18N

        jPanel_cadastro.setBackground(new java.awt.Color(25, 226, 226));
        jPanel_cadastro.setToolTipText("jPanel_cadastro\n");
        jPanel_cadastro.setName("jPanel_cadastro"); // NOI18N

        agencia.setText("Agência");

        inputAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAgenciaActionPerformed(evt);
            }
        });

        numero.setText("Número");

        inputNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumeroActionPerformed(evt);
            }
        });

        saldo.setText("Saldo");

        inputSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSaldoActionPerformed(evt);
            }
        });

        inputLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLimiteActionPerformed(evt);
            }
        });

        limite.setText("Limite");

        jTextAreaCadastroContas.setColumns(20);
        jTextAreaCadastroContas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCadastroContas);

        nome.setText("Nome");

        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        inputCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCPFActionPerformed(evt);
            }
        });

        cpf.setText("CPF");

        inputEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEnderecoActionPerformed(evt);
            }
        });

        endereco.setText("Endereco");

        inputTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefoneActionPerformed(evt);
            }
        });

        telefone.setText("Telefone");

        listarContas.setText("Listar");
        listarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarContasActionPerformed(evt);
            }
        });

        buttonLimparCampos.setText("Limpar campos");
        buttonLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparCamposActionPerformed(evt);
            }
        });

        salvarContas.setText("Add Conta");
        salvarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarContasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_cadastroLayout = new javax.swing.GroupLayout(jPanel_cadastro);
        jPanel_cadastro.setLayout(jPanel_cadastroLayout);
        jPanel_cadastroLayout.setHorizontalGroup(
            jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_cadastroLayout.createSequentialGroup()
                        .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endereco)
                            .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_cadastroLayout.createSequentialGroup()
                                        .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(agencia)
                                            .addComponent(inputAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(numero)
                                            .addComponent(inputNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(saldo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(limite)
                                            .addComponent(inputLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel_cadastroLayout.createSequentialGroup()
                                        .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(inputEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                            .addComponent(inputNome, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nome, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cpf)
                                            .addComponent(inputCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(telefone)
                                            .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_cadastroLayout.createSequentialGroup()
                        .addComponent(salvarContas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(listarContas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonLimparCampos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_cadastroLayout.setVerticalGroup(
            jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_cadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_cadastroLayout.createSequentialGroup()
                        .addComponent(agencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_cadastroLayout.createSequentialGroup()
                        .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(limite)
                            .addComponent(saldo)
                            .addComponent(numero))
                        .addGap(38, 38, 38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_cadastroLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_cadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarContas)
                    .addComponent(buttonLimparCampos)
                    .addComponent(salvarContas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel_exclusao_contas.setBackground(new java.awt.Color(59, 231, 28));

        comboBoxContas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxContasItemStateChanged(evt);
            }
        });
        comboBoxContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxContasActionPerformed(evt);
            }
        });

        jLabel1.setText("Contas");

        buttonExcluirConta.setText("Excluir conta");
        buttonExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirContaActionPerformed(evt);
            }
        });

        buttonEditarConta1.setText("Editar conta");
        buttonEditarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarConta1ActionPerformed(evt);
            }
        });

        jListTitulares.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulares"));
        jListTitulares.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTitularesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListTitulares);

        jButtonEditTitular.setText("Edit.Titular");
        jButtonEditTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditTitularActionPerformed(evt);
            }
        });

        jButtonAddTitular.setText("Add Titular");
        jButtonAddTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTitularActionPerformed(evt);
            }
        });

        jButtonExcluiTitular.setText("Excluir Titular");
        jButtonExcluiTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluiTitularActionPerformed(evt);
            }
        });

        jButtonLog.setText("LOG");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_exclusao_contasLayout = new javax.swing.GroupLayout(jPanel_exclusao_contas);
        jPanel_exclusao_contas.setLayout(jPanel_exclusao_contasLayout);
        jPanel_exclusao_contasLayout.setHorizontalGroup(
            jPanel_exclusao_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_exclusao_contasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel_exclusao_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_exclusao_contasLayout.createSequentialGroup()
                        .addComponent(buttonEditarConta1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonExcluirConta))
                    .addComponent(jScrollPane2)
                    .addComponent(comboBoxContas, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_exclusao_contasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel_exclusao_contasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonAddTitular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditTitular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluiTitular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel_exclusao_contasLayout.setVerticalGroup(
            jPanel_exclusao_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_exclusao_contasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_exclusao_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExcluirConta)
                    .addComponent(buttonEditarConta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_exclusao_contasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditTitular)
                    .addComponent(jButtonAddTitular)
                    .addComponent(jButtonExcluiTitular)
                    .addComponent(jButtonLog))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(228, 28, 185));

        jComboBoxFuncionarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFuncionariosItemStateChanged(evt);
            }
        });
        jComboBoxFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncionariosActionPerformed(evt);
            }
        });

        jLabelFuncionario.setText("Funcionário");

        buttonGroupFormasPagamento.add(jRadioButtonDepositar);
        jRadioButtonDepositar.setText("Depositar");
        jRadioButtonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDepositarActionPerformed(evt);
            }
        });

        buttonGroupFormasPagamento.add(jRadioButtonSacar);
        jRadioButtonSacar.setText("Sacar\n");
        jRadioButtonSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSacarActionPerformed(evt);
            }
        });

        buttonGroupFormasPagamento.add(jRadioButtonTransferir);
        jRadioButtonTransferir.setText("Transferir");
        jRadioButtonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTransferirActionPerformed(evt);
            }
        });

        jLabelContaDestino.setText("Conta Destino");

        jLabelValor.setText("Valor");

        jButtonExecutarOperacao.setText("Executar operação");
        jButtonExecutarOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarOperacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxFuncionarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxContaDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButtonSacar)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonDepositar)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonTransferir)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelValor)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldValor)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelContaDestino)
                            .addComponent(jLabelFuncionario))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonExecutarOperacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelFuncionario)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDepositar)
                    .addComponent(jRadioButtonSacar)
                    .addComponent(jRadioButtonTransferir)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabelContaDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExecutarOperacao)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_exclusao_contas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_exclusao_contas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_cadastro.getAccessibleContext().setAccessibleName("jPanel_cadastro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefoneActionPerformed

    private void inputEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEnderecoActionPerformed

    private void inputCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCPFActionPerformed

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeActionPerformed

    private void inputLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLimiteActionPerformed

    private void inputSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSaldoActionPerformed

    private void inputNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumeroActionPerformed

    private void inputAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAgenciaActionPerformed

    private void salvarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarContasActionPerformed
        int agenciA = Integer.parseInt( inputAgencia.getText() );
        int numerO = Integer.parseInt( inputNumero.getText() );
        float saldO = Float.parseFloat( inputSaldo.getText() );
        float limitE = Float.parseFloat( inputLimite.getText() );
        String nomE = inputNome.getText();
        String telefonE = inputTelefone.getText();
        String enderecO = inputEndereco.getText();
        String cpF = inputCPF.getText();
        
        contas.add( new Conta(numerO, agenciA, saldO, limitE, nomE, cpF, enderecO, telefonE) );
        
        inputAgencia.setText("");
        inputNumero.setText("");
        inputSaldo.setText("");
        inputLimite.setText("");
        inputNome.setText("");
        inputTelefone.setText("");
        inputEndereco.setText("");
        inputCPF.setText("");
        JOptionPane.showMessageDialog(null, "Conta registrada com sucesso");
        
    }//GEN-LAST:event_salvarContasActionPerformed

    private void listarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarContasActionPerformed
        atualizarTela();
        atualizaTela2();
        jTextAreaCadastroContas.setText("");
        contas.forEach(c -> {
            jTextAreaCadastroContas.append("Agência "+c.getAgencia());
            jTextAreaCadastroContas.append("\nContas: "+c.getNumero());
            jTextAreaCadastroContas.append("\nSaldo: "+c.getSaldo());
            jTextAreaCadastroContas.append("\nLimite: "+c.getLimite());
//            jTextAreaCadastroContas.append("\nTitular: "+c.getTitular().getNome());
//            jTextAreaCadastroContas.append("\nCPF:"+c.getTitular().getCpf());
            c.getTitular().forEach(t->{
                jTextAreaCadastroContas.append("\nNome: "+t.getNome() + " CPF: "+t.getCpf());
            });
            jTextAreaCadastroContas.append("\n\n");
            
          });
    }//GEN-LAST:event_listarContasActionPerformed

    private void comboBoxContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxContasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxContasActionPerformed

    private void buttonExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirContaActionPerformed
        Conta auxConta = (Conta) comboBoxContas.getSelectedItem();
        contas.remove(auxConta);
        
        //LIMPANDO CAMPOS
        inputAgencia.setText("");
        inputNumero.setText("");
        inputSaldo.setText("");
        inputLimite.setText("");
        inputNome.setText("");
        inputTelefone.setText("");
        inputEndereco.setText("");
        inputCPF.setText("");
        JOptionPane.showMessageDialog(null, "Contas excluida com sucesso"); 
        atualizarTela();
        limparCampos();
    }//GEN-LAST:event_buttonExcluirContaActionPerformed

    private void buttonEditarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarConta1ActionPerformed
        Conta auxConta = (Conta) comboBoxContas.getSelectedItem();
        //CAPITURANDO OS DADOS DA CONTA PARA ALTERAR
            int agenciA = Integer.parseInt( inputAgencia.getText() );
            int numerO = Integer.parseInt( inputNumero.getText() );
            float saldO = Float.parseFloat( inputSaldo.getText() );
            float limitE = Float.parseFloat( inputLimite.getText() );
            String nomE = inputNome.getText();
            String telefonE = inputTelefone.getText();
            String enderecO = inputEndereco.getText();
            String cpF = inputCPF.getText();
            
        //ALTERANDO DADOS DA CONTA
             auxConta.setAgencia(agenciA);
             auxConta.setNumero(numerO);
             auxConta.setSaldo(saldO);
             auxConta.setLimite(limitE);
             auxConta.getTitular().forEach(t->{
                t.setNome(nomE);
                t.setEndereco(enderecO);
                t.setTelefone(telefonE);
                t.setCpf(cpF);
            });
         
        //LIMPANDO CAMPOS
        inputAgencia.setText("");
        inputNumero.setText("");
        inputSaldo.setText("");
        inputLimite.setText("");
        inputNome.setText("");
        inputTelefone.setText("");
        inputEndereco.setText("");
        inputCPF.setText("");
        JOptionPane.showMessageDialog(null, "Dados alterados com sucesso"); 
             
    }//GEN-LAST:event_buttonEditarConta1ActionPerformed

    private void comboBoxContasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxContasItemStateChanged
        Conta auxConta = (Conta) comboBoxContas.getSelectedItem();
        if(auxConta != null){
            inputAgencia.setText(""+auxConta.getAgencia());
            inputNumero.setText(""+auxConta.getNumero());
            inputSaldo.setText(""+auxConta.getSaldo());
            inputLimite.setText(""+auxConta.getLimite());
            
            
            
            //carrega titulares no jListTitulares
            DefaultListModel<Cliente> model = new DefaultListModel<>();
            auxConta.getTitular().forEach(ti->{
                model.addElement((banco.Cliente) ti);
//                inputNome.setText(""+ti.getNome());
//                inputCPF.setText(""+ti.getCpf()); 
//                inputEndereco.setText(""+ti.getEndereco());
//                inputTelefone.setText(""+ti.getTelefone());
            });
            jListTitulares.setModel(model);
            
        }
            
    }//GEN-LAST:event_comboBoxContasItemStateChanged

    private void buttonLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_buttonLimparCamposActionPerformed

    private void jButtonEditTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditTitularActionPerformed
        // MÉTODO PARA EDITAR O TITULAR
        
        // IDENTIFICA TITULAR SELECIONADO
        Cliente auxCliente = (Cliente) jListTitulares.getSelectedValue();
        auxCliente.setNome(inputNome.getText());
        auxCliente.setEndereco(inputEndereco.getText());
        auxCliente.setCpf(inputCPF.getText());
        auxCliente.setTelefone(inputTelefone.getText());
        
        //ATUALIZA LISTA DE TITULARES
        comboBoxContasItemStateChanged(null);
        
        //limpa tela
        inputNome.setText("");
        inputTelefone.setText("");
        inputEndereco.setText("");
        inputCPF.setText("");
    }//GEN-LAST:event_jButtonEditTitularActionPerformed

    private void jButtonAddTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTitularActionPerformed
        // MÉTODO PARA ADICIONAR O TITULAR
        String nome = inputNome.getText();
        String telefone = inputTelefone.getText();
        String endereco = inputEndereco.getText();
        String cpf = inputCPF.getText();
        
        //pega a conta selecionada do seletor e adiciona um novo titular
        Conta auxConta = (Conta) comboBoxContas.getSelectedItem();
        auxConta.getTitular().add(new Cliente(nome,cpf, endereco, telefone));
        
        //executa evento apra atualizar lista de titulares da conta
        comboBoxContasItemStateChanged(null);
        
        //limpar tela
        inputNome.setText("");
        inputTelefone.setText("");
        inputEndereco.setText("");
        inputCPF.setText("");
    }//GEN-LAST:event_jButtonAddTitularActionPerformed

    private void jButtonExcluiTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluiTitularActionPerformed
        // MÉTODO PARA EXCLUIR O TITULAR
        // CAPTURA CONTA
        Conta auxConta = (Conta) comboBoxContas.getSelectedItem();
        
        //VERIFICA SE A CONTA TEM MAIS DE UM TITULAR
        if(auxConta.getTitular().size()>1){
            //exclui conta
            auxConta.getTitular().remove(jListTitulares.getSelectedValue());
        }
        //atualiza listagem de titulares
        comboBoxContasItemStateChanged(null);
        
    }//GEN-LAST:event_jButtonExcluiTitularActionPerformed

    private void jListTitularesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTitularesValueChanged
        // SELECIONA TITULAR PARA DEPOIS EDITALO
        //limpar tela
        inputNome.setText("");
        inputTelefone.setText("");
        inputEndereco.setText("");
        inputCPF.setText("");
        
        Cliente auxCliente = (Cliente) jListTitulares.getSelectedValue();
        if(auxCliente != null){
            inputNome.setText(auxCliente.getNome());
            inputTelefone.setText(auxCliente.getTelefone());
            inputEndereco.setText(auxCliente.getEndereco());
            inputCPF.setText(auxCliente.getCpf()); 
        }
    }//GEN-LAST:event_jListTitularesValueChanged

    private void jRadioButtonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDepositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDepositarActionPerformed

    private void jRadioButtonSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSacarActionPerformed

    private void jRadioButtonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTransferirActionPerformed

    private void jComboBoxFuncionariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFuncionariosItemStateChanged
        //Atualiza funcionarios tela banco
        Funcionario auxFuncionario = (Funcionario) jComboBoxFuncionarios.getSelectedItem();
        
        
    }//GEN-LAST:event_jComboBoxFuncionariosItemStateChanged

    private void jComboBoxFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncionariosActionPerformed
        
    }//GEN-LAST:event_jComboBoxFuncionariosActionPerformed

    private void jButtonExecutarOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarOperacaoActionPerformed
        
        Conta auxConta = (Conta) comboBoxContas.getSelectedItem();
        Cliente auxTitular = (Cliente) jListTitulares.getSelectedValue();
        Funcionario auxFuncionario = (Funcionario) jComboBoxFuncionarios.getSelectedItem();
        Conta auxContaDestino = (Conta) jComboBoxContaDestino.getSelectedItem();
//        StringBuilder titularesCpf = new StringBuilder();
//        auxConta.getTitular().forEach(c->{
//                titularesCpf.append("Titulares"+c.getCpf());
//            });
        float auxValor = Float.parseFloat(jTextFieldValor.getText());
        
        String validaMatricula;
        
       
        if ( !auxFuncionario.getAutentica(JOptionPane.showInputDialog("Senha funcionário:")) ){
            JOptionPane.showMessageDialog(null, "Senha funcionário errada!!!");
            return;
        }
//        if(!auxTitular.getAutentica(JOptionPane.showInputDialog("Senha cliente: "))){
//            JOptionPane.showMessageDialog(null, "Senha funcionário errada!");
//            return;
//        };
        
        if(jRadioButtonSacar.isSelected()){
            if(auxConta.sacar(auxValor, auxFuncionario)){
                
                  auxConta.gravaLog("Sacar", "OK", auxValor, auxConta.getNumero(), auxFuncionario.getMatricula());
            }else{
              auxConta.gravaLog("Sacar", "ERRO", auxValor, auxConta.getNumero(), auxFuncionario.getMatricula());  
            }
        }else if(jRadioButtonDepositar.isSelected()){
            System.out.println("aqui");
            if(auxConta.depositar(auxValor, auxFuncionario)){
                  auxConta.gravaLog("Depositar", "OK", auxValor, auxConta.getNumero(), auxFuncionario.getMatricula());
            }else{
              auxConta.gravaLog("Depositar", "ERRO", auxValor, auxConta.getNumero(), auxFuncionario.getMatricula());  
            }
        }else if(jRadioButtonTransferir.isSelected()){
            if(auxConta.transferir(auxContaDestino, auxValor, auxFuncionario)){
                  auxConta.gravaLog("Transferir", "OK", auxValor, auxConta.getNumero(), auxFuncionario.getMatricula());
                  auxContaDestino.gravaLog("Transferir", "OK", auxValor, auxConta.getNumero(), auxFuncionario.getMatricula());
            }else{
              auxConta.gravaLog("Transferir", "ERRO", auxValor, auxConta.getNumero(), auxFuncionario.getMatricula());  
            }
        }
        
        listarContas.doClick();
    }//GEN-LAST:event_jButtonExecutarOperacaoActionPerformed

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        Conta auxConta = (Conta) comboBoxContas.getSelectedItem();
        
        jTextAreaCadastroContas.setText("Log conta: "+auxConta.getNumero()+"\n");
        jTextAreaCadastroContas.append(auxConta.getLog().toString());
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void atualizarTela(){
        comboBoxContas.removeAllItems();
        contas.forEach(c -> {
            comboBoxContas.addItem(c);
        });
        
        jComboBoxContaDestino.removeAllItems();
        contas.forEach(d -> {
            jComboBoxContaDestino.addItem(d);
        });
        
        jComboBoxFuncionarios.removeAllItems();
        funcionarios.forEach(f -> {
            jComboBoxFuncionarios.addItem(f);
        });
    }
    
    
    public void limparCampos(){
        //LIMPANDO CAMPOS
        inputAgencia.setText("");
        inputNumero.setText("");
        inputSaldo.setText("");
        inputLimite.setText("");
        inputNome.setText("");
        inputTelefone.setText("");
        inputEndereco.setText("");
        inputCPF.setText("");
    }
    
   private void atualizaTela2() {//populaos JComboBoxde contas e conta de destino
       comboBoxContas.removeAllItems();
       jComboBoxContaDestino.removeAllItems();
       contas.forEach(c -> {
            comboBoxContas.addItem(c);
            jComboBoxContaDestino.addItem(c);
       });
        
        //populaos Funcionarios
        jComboBoxFuncionarios.removeAllItems();
       funcionarios.forEach(f -> {
           jComboBoxFuncionarios.addItem(f);
       });

        //mostra os dados no textarea
       jTextAreaCadastroContas.setText("");
       
       contas.forEach(conta -> {jTextAreaCadastroContas.append("Agência: " + conta.getAgencia());
       jTextAreaCadastroContas.append("\nContanº: " + conta.getNumero());
       jTextAreaCadastroContas.append("\nSaldo: " + NumberFormat.getCurrencyInstance().format(conta.getSaldo()));
       jTextAreaCadastroContas.append("\nLimite: " + NumberFormat.getCurrencyInstance().format(conta.getLimite()));
       jTextAreaCadastroContas.append("\nTitulares: ");
       conta.getTitular().forEach(t -> {jTextAreaCadastroContas.append("\n* Nome: " + t.getNome() + " CPF: " + t.getCpf());});
       jTextAreaCadastroContas.append("\n\n");}); //limpa os camposjTextFieldAgencia.setText(""); jTextFieldNumero.setText(""); jTextFieldSaldo.setText("");jTextFieldLimite.setText(""); jTextFieldNome.setText(""); jTextFieldTelefone.setText("");jTextFieldEndereco.setText(""); jTextFieldCpf.setText("");}
   
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agencia;
    private javax.swing.JButton buttonEditarConta1;
    private javax.swing.JButton buttonExcluirConta;
    private javax.swing.ButtonGroup buttonGroupFormasPagamento;
    private javax.swing.JButton buttonLimparCampos;
    private javax.swing.JComboBox<Conta> comboBoxContas;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel endereco;
    private javax.swing.JTextField inputAgencia;
    private javax.swing.JTextField inputCPF;
    private javax.swing.JTextField inputEndereco;
    private javax.swing.JTextField inputLimite;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputNumero;
    private javax.swing.JTextField inputSaldo;
    private javax.swing.JTextField inputTelefone;
    private javax.swing.JButton jButtonAddTitular;
    private javax.swing.JButton jButtonEditTitular;
    private javax.swing.JButton jButtonExcluiTitular;
    private javax.swing.JButton jButtonExecutarOperacao;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JComboBox<Object> jComboBoxContaDestino;
    private javax.swing.JComboBox<Object> jComboBoxFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContaDestino;
    private javax.swing.JLabel jLabelFuncionario;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JList<Cliente> jListTitulares;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_cadastro;
    private javax.swing.JPanel jPanel_exclusao_contas;
    private javax.swing.JRadioButton jRadioButtonDepositar;
    private javax.swing.JRadioButton jRadioButtonSacar;
    private javax.swing.JRadioButton jRadioButtonTransferir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaCadastroContas;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JLabel limite;
    private javax.swing.JButton listarContas;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel saldo;
    private javax.swing.JButton salvarContas;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
